### ISSUE TITLE
Aussie Broadband Meter

### ISSUE THREAD

**Issue by simonwood0609** [DavidFW1960/home-assistant#1]
Hi David, wasn't sure where/how to contact you.

First of all, wow!  Some fantastic inspiration for my Home Assistant components/cards here.  Great setup!  We utilise a lot of the same services (Sonarr/Radarr/etc/Aussie Broadband/etc).

I have so many questions - for now I'll look through your repository to try and see how you've configured things.

Your ABB Usage metre - is that using [this component](https://github.com/DavidFW1960/Aussie-Broadband-Usage-Meter) which seems to be for Rain Metre?

**Comment by DavidFW1960** [comment]
Hi Simon, thanks!

I have 2 ABB usage meters. The one for Home Assistant is here https://github.com/DavidFW1960/ABB-Home-Assistant-Usage

The one you linked is a standalone Windows usage meter for ABB.

Edited to add: feel free to ask any questions....

**Comment by simonwood0609** [comment]
Thanks!  Love it - will get to work on the ABB meter.

1.   What component are you using to get the CVC Data?
2.   What component & LoveLace Card are you using to get the fire-warning-meter?
3.   Are you aware of any fuel-watch components for Victoria?  I can't find any. :(

**Comment by DavidFW1960** [comment]
Just a camera component. You need to get the URL for the CVC from the ABB webpage. I actually recently switched to Superloop but it's similar to that:
```
# Superloop CVC Capacity
camera:
  - platform: generic
    name: Superloop CVC Capacity
    still_image_url: !secret superloop_cvc
```

Fire warning is using a package in the packages folder nswfireandincidents.yaml
If you use my custom BOM FTP component and Weather Card you can get the fire warning data and still use the card you see on my github - check my ui-lovelace.yaml for that card - I made the graphics and you can download those as well. (My BOM stuff is in HACS)

Not aware of fuel watch for Vic sorry.

**Comment by simonwood0609** [comment]
Any chance we could connect on Discord or Skype for continued conversation?  I can figure most things out on my own, just the occasional question here and there would be very helpful though.

**Comment by DavidFW1960** [comment]
if you join the Home Assistant discord, I have the same username there as I do here
