### ISSUE TITLE
Questions about 2FA / 3FA

### ISSUE THREAD

**Issue by stbeep1** [DavidFW1960/home-assistant#3]
# Auth & 2FA
  auth_mfa_modules:
    - type: notify
    - type: totp

What's this code for? 😳I am interested as wanted to implement MFA or 3FA for my HA server. Currently I only use google authenticator as ￼the 2FA for my HA servers. What are the differences between 2FA and 'notify'? Thank you 🙏🏻

**Comment by DavidFW1960** [comment]
There's 2 types of 2FA in HA. One uses an authenticator App (the totp one) and the other sends a notification via I *think* the iOS app. So I have both in my config and use whichever is most convenient at the time.
I rarely use either due to authorised networks anyway...
