### ISSUE TITLE
Radarr integration not working 

### ISSUE THREAD

**Issue by spicerackk** [DavidFW1960/home-assistant#4]
I grabbed your radarr custom_component folder and imported it into my HA instance, but am getting this showing on the integration when I try to configure it:

`Retrying setup: Request exception for 'http://http://192.168.86.245:7878/radarr/api/v3/system/status' with - Cannot connect to host http:80 ssl:False [Try again]`

I am unsure of what else I need to do to configure it properly, I have added the official integration from HA as well with no luck.

**Comment by DavidFW1960** [comment]
you deleted all YAML configuration right?
Delete all yaml and restart home assistant. Then add radarr from the GUI
![image](https://user-images.githubusercontent.com/36390762/162654823-84c2f4c5-1cc5-451c-b051-6ee915e514fa.png)
Just entering the protocol/url/port looks like yours is http://192.168.86.245:7878 and your API. I haven't tried with ssl.
You downloaded all the files from here https://github.com/DavidFW1960/home-assistant/tree/master/custom_components/radarr in 'raw' mode?

**Comment by DavidFW1960** [comment]
the official HA integration also only works with api v2 (radar 3) radarr 4 uses api v3 and won't work except with my custom component.
