### ISSUE TITLE
FTTP package

### ISSUE THREAD

**Issue by vorwd** [DavidFW1960/home-assistant#6]
Hi mate,

Just an suggestion, those that are aware of how to identify a location from a LOCID could use that info maliciously -- wasn't sure how else to suggest it's removal without a issue submission.  

Thanks for sharing your config files as they've proven quite useful on my end for the fuel and transport integrations.  

-J

**Comment by DavidFW1960** [comment]
Thanks for the suggestion. Not sure how it could be used and I doubt anyone would want to anyway.

**Comment by vorwd** [comment]
In regard to:
> Not sure how it could be used....

Two ways:

1. https://www.aussiebroadband.com.au/network/poi-checker/  <-- can just pop it in here (works with AVCs that aren't ABB), or;
2. curl "https://places.nbnco.net.au/places/v1/details/LOC000032320593" -H "Referer: https://www.nbnco.com.au/"

`"https://places.nbnco.net.au/places/v1/details/LOC000171029247" -H "Referer: https://www.nbnco.com.au/"
{"timestamp":1719797988134,"location":{"id":"LOC000171029247","formattedAddress":"ROOM FIP 80 PACIFIC HWY NORTH SYDNEY NSW 2060 Australia","latitude":-33.84077502,"longitude":151.20815943,"postcode":"2060"},"servingArea":{"csaId":"CSA200000000824","techType":"FTTB","serviceType":"Fixed line","serviceStatus":"available","serviceCategory":"brownfields","rfsMessage":"Oct 2017","description":"80 PACIFIC HWY NORTH SYDNEY, NSW 2060"},"addressDetail":{"id":"LOC000171029247","csaId":"CSA200000000824","latitude":-33.84077502,"longitude":151.20815943,"addressStatus":"FTTB","serviceType":"Fixed line","serviceStatus":"available","serviceCategory":"brownfields","disconnectionStatus":"DEFAULT","techType":"FTTB","serviceabilityMessage":"","formattedAddress":"ROOM FIP 80 PACIFIC HWY NORTH SYDNEY NSW 2060 Australia","locality":"NORTH SYDNEY","statusMessage":"connected-true","ee":false}}`

<br>

And, while yes, I'd say you are probably correct in your thinking, and unlikely to experience any adverse event: 
> ...and I doubt anyone would want to anyway.

I looked at it like this... you went through the trouble of putting your private ipv4 address into your !secrets file (although I did see this/a private range included in your sysmonitor.yaml, FYI) .  You also excluded your MQTT yaml file, which potentially shares your WAN address based on your dashboard configs... and using !secret for your ABB CVC and !secret for usernames (which, yes, I certainly agree with)...

I guess the reason for sharing it with you was, If you went through the trouble of securing your digital environment, I see no difference in the need to secure your physical environment as well (you do have an alarm system it seems) -- your use of your suburb and closest bus stop aside, (as these aren't really pin pointing who you are) (I'm down on The Peninsula, by the way :-p ), I felt the LODIC exposure was important to callout, as with a simple curl string, someone with malicious intent has your full address.  

All the best, and have a happy and secure day! :-)
